const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('index.html','utf8'),dashboard=fs.readFileSync('dashboard.html','utf8');
assert.ok(html.includes('data:image/png;base64,')&&!html.includes('/*__'));
assert.ok(dashboard.includes('ESTAT.HEALTH.UNMET.ACCESS'));
assert.ok(html.includes('width:200px')&&html.includes('dp-tool-grid'));
assert.ok(html.includes('page=comparison')&&html.includes('ESTAT.INTERNET.HOUSEHOLDS'));
assert.ok(dashboard.includes('href="./"'));
const source=html.match(/<script>([\s\S]*?)<\/script>/)[1];
function element(dataset={}){return {dataset,events:{},attrs:{},innerHTML:'',textContent:'',addEventListener(k,f){this.events[k]=f},setAttribute(k,v){this.attrs[k]=v}}}
const nodes=new Map(),mottos=[0,1,2].map(n=>element({motto:String(n)}));
for(const k of ['#dp-label','#dp-metrics','#dp-enter','#dp-challenge','#dp-footer','#dp-motto','.dp-lang','.dp-circle','.dp-pause'])nodes.set(k,element());
const copyNode=element({toolCopy:'comparison'}),toolLink=element({toolPage:'comparison'});toolLink.href='dashboard.html#page=comparison';toolLink.getAttribute=()=>toolLink.href;
const root={querySelector:k=>nodes.get(k),querySelectorAll:k=>k==='[data-motto]'?mottos:k==='[data-tool-copy]'?[copyNode]:k==='[data-tool-page]'?[toolLink]:[]};let interval=null,delay=null,redirect=null;
const document={hidden:false,events:{},getElementById:()=>root,addEventListener(k,f){this.events[k]=f}};
const context={document,location:{hash:'#indicator=FP.CPI.TOTL.ZG',replace(x){redirect=x}},URLSearchParams,setInterval(f,ms){interval=f;delay=ms;return 1},clearInterval(){interval=null}};
vm.runInNewContext(source,context);
assert.equal(redirect,'dashboard.html#indicator=FP.CPI.TOTL.ZG');assert.equal(delay,5000);
assert.match(nodes.get('#dp-motto').innerHTML,/VOTING/);
interval();assert.match(nodes.get('#dp-motto').innerHTML,/PROMISES/);
interval();assert.match(nodes.get('#dp-motto').innerHTML,/VALUES/);
interval();assert.match(nodes.get('#dp-motto').innerHTML,/VOTING/);
mottos[2].events.click();assert.match(nodes.get('#dp-motto').innerHTML,/VALUES/);
nodes.get('.dp-pause').events.click();assert.equal(interval,null);
nodes.get('.dp-pause').events.click();assert.equal(delay,5000);assert.ok(interval);
document.hidden=true;document.events.visibilitychange();assert.equal(interval,null);
document.hidden=false;document.events.visibilitychange();assert.ok(interval);
nodes.get('.dp-lang').events.click();assert.match(nodes.get('#dp-motto').innerHTML,/ΨΗΦΙΣΤΕ/);assert.equal(nodes.get('.dp-circle').href,'dashboard.html#lang=el');assert.match(toolLink.href,/page=comparison/);assert.match(toolLink.href,/lang=el/);assert.equal(copyNode.textContent,'Σύγκριση κυβερνήσεων');
console.log('Landing: timed 1–2–3 loop, manual selection, pause/resume, hidden-tab pause, bilingual entry and old links passed');
