"""Editorial labels and category mappings; all observations come from official APIs."""
COUNTRIES = {
    'GRC': {'en': 'Greece', 'el': 'Ελλάδα', 'color': '#086a88'},
    'EUU': {'en': 'European Union', 'el': 'Ευρωπαϊκή Ένωση', 'color': '#d69624'},
    'DEU': {'en': 'Germany', 'el': 'Γερμανία', 'color': '#6953a5'},
    'FRA': {'en': 'France', 'el': 'Γαλλία', 'color': '#b34f72'},
    'ESP': {'en': 'Spain', 'el': 'Ισπανία', 'color': '#d46534'},
    'PRT': {'en': 'Portugal', 'el': 'Πορτογαλία', 'color': '#32826e'},
}
CATEGORIES = [
 ('economy','Economy','Οικονομία'), ('health','Health','Υγεία'),
 ('education','Education','Παιδεία'), ('environment','Environment','Περιβάλλον'),
 ('infrastructure','Infrastructure','Υποδομές'), ('governance','Governance & society','Διακυβέρνηση & κοινωνία'),
 ('business','Business & innovation','Επιχειρήσεις & καινοτομία'),
 ('wellbeing','Well-being & quality of life','Ευημερία & ποιότητα ζωής'),
 ('culture','Culture & leisure','Πολιτισμός & αναψυχή'),
 ('housing','Housing & living conditions','Στέγαση & συνθήκες διαβίωσης'),
 ('security','Personal security & resilience','Ασφάλεια & ανθεκτικότητα'),
 ('digital','Digital society','Ψηφιακή κοινωνία'),
 ('demographics','Demographics & population','Δημογραφία & πληθυσμός'),
 ('finance','Public finance & debt','Δημόσια οικονομικά & χρέος'),
 ('technology','Technological readiness','Τεχνολογική ετοιμότητα'),
 ('justice','Justice & rule of law','Δικαιοσύνη & κράτος δικαίου'),
 ('energy','Energy & resources','Ενέργεια & πόροι'),
 ('transport','Transportation & mobility','Μεταφορές & κινητικότητα'),
 ('resilience','Resilience & sustainability','Ανθεκτικότητα & βιωσιμότητα'),
 ('international','International engagement','Διεθνής παρουσία'),
 ('freedom','Freedom & participation','Ελευθερία & συμμετοχή'),
]
# code, short English label, Greek label, unit, categories, change unit.
# Changes in percentages are percentage points, never percentage growth.
ROWS = [
 ('NY.GDP.MKTP.KD.ZG','GDP growth','Ανάπτυξη ΑΕΠ','%','economy','pp'),
 ('NY.GDP.PCAP.KD','GDP per capita','Κατά κεφαλήν ΑΕΠ','constant 2015 US$','economy,wellbeing','absolute'),
 ('FP.CPI.TOTL.ZG','Consumer price inflation','Πληθωρισμός','%','economy,wellbeing','pp'),
 ('SL.UEM.TOTL.ZS','Unemployment','Ανεργία','%','economy,wellbeing','pp'),
 ('SL.UEM.1524.ZS','Youth unemployment','Ανεργία νέων','%','economy,wellbeing','pp'),
 ('SL.TLF.CACT.FE.ZS','Female labour participation','Συμμετοχή γυναικών στην εργασία','%','economy,governance,freedom','pp'),
 ('NE.TRD.GNFS.ZS','Trade openness','Εμπόριο ως ποσοστό του ΑΕΠ','% of GDP','economy,international','pp'),
 ('BX.KLT.DINV.WD.GD.ZS','Foreign direct investment','Άμεσες ξένες επενδύσεις','% of GDP','economy,business,international','pp'),
 ('NE.EXP.GNFS.ZS','Exports of goods & services','Εξαγωγές αγαθών & υπηρεσιών','% of GDP','economy,international','pp'),
 ('SP.DYN.LE00.IN','Life expectancy','Προσδόκιμο ζωής','years','health,wellbeing','absolute'),
 ('SP.DYN.IMRT.IN','Infant mortality','Βρεφική θνησιμότητα','per 1,000 live births','health','absolute'),
 ('SH.STA.MMRT','Maternal mortality','Μητρική θνησιμότητα','per 100,000 live births','health','absolute'),
 ('SH.MED.BEDS.ZS','Hospital beds','Νοσοκομειακές κλίνες','per 1,000 people','health,infrastructure','absolute'),
 ('SH.XPD.CHEX.GD.ZS','Health expenditure','Δαπάνες υγείας','% of GDP','health,finance','pp'),
 ('SH.XPD.CHEX.PC.CD','Health spending per person','Δαπάνες υγείας ανά κάτοικο','current US$','health','absolute'),
 ('SH.IMM.MEAS','Measles immunisation','Εμβολιασμός ιλαράς','% of children 12–23 months','health,resilience','pp'),
 ('SE.XPD.TOTL.GD.ZS','Public education spending','Δημόσιες δαπάνες παιδείας','% of GDP','education,finance','pp'),
 ('SE.TER.ENRR','Tertiary enrolment, gross','Εγγραφές στην τριτοβάθμια, ακαθάριστο ποσοστό','%','education','pp'),
 ('SE.SEC.ENRR','Secondary enrolment, gross','Εγγραφές στη δευτεροβάθμια, ακαθάριστο ποσοστό','%','education','pp'),
 ('SE.PRM.ENRL.TC.ZS','Primary pupil–teacher ratio','Μαθητές ανά εκπαιδευτικό πρωτοβάθμιας','pupils per teacher','education','absolute'),
 ('AG.LND.FRST.ZS','Forest area','Δασική έκταση','% of land area','environment,resilience','pp'),
 ('EN.ATM.PM25.MC.M3','PM2.5 air pollution','Ατμοσφαιρική ρύπανση PM2.5','µg/m³','environment,health,housing','absolute'),
 ('EN.GHG.CO2.PC.CE.AR5','CO₂ emissions per person','Εκπομπές CO₂ ανά κάτοικο','t CO₂e/person','environment,energy,resilience','absolute'),
 ('ER.LND.PTLD.ZS','Protected terrestrial areas','Προστατευόμενες χερσαίες περιοχές','% of land area','environment,resilience','pp'),
 ('EG.ELC.ACCS.ZS','Access to electricity','Πρόσβαση σε ηλεκτρικό ρεύμα','% of population','infrastructure,housing','pp'),
 ('IT.NET.BBND.P2','Fixed broadband subscriptions','Συνδρομές σταθερής ευρυζωνικότητας','per 100 people','infrastructure,digital,technology','absolute'),
 ('IT.NET.USER.ZS','Internet use','Χρήση διαδικτύου','% of population','digital,technology','pp'),
 ('IT.CEL.SETS.P2','Mobile subscriptions','Συνδρομές κινητής τηλεφωνίας','per 100 people','digital,infrastructure','absolute'),
 ('IS.RRS.TOTL.KM','Rail network length','Μήκος σιδηροδρομικού δικτύου','km','infrastructure,transport','absolute'),
 ('GB.XPD.RSDV.GD.ZS','Research & development spending','Δαπάνες έρευνας & ανάπτυξης','% of GDP','business,technology','pp'),
 ('IP.PAT.RESD','Resident patent applications','Αιτήσεις διπλωμάτων ευρεσιτεχνίας κατοίκων','applications','business,technology','absolute'),
 ('TX.VAL.TECH.MF.ZS','High-technology exports','Εξαγωγές υψηλής τεχνολογίας','% of manufactured exports','business,technology,international','pp'),
 ('SI.POV.GINI','Income inequality (Gini)','Εισοδηματική ανισότητα (Gini)','0–100 index','wellbeing,governance','absolute'),
 ('ST.INT.ARVL','International tourist arrivals','Διεθνείς τουριστικές αφίξεις','arrivals','culture,international','absolute'),
 ('ST.INT.RCPT.CD','International tourism receipts','Έσοδα διεθνούς τουρισμού','current US$','culture,international','absolute'),
 ('SH.H2O.SMDW.ZS','Safely managed drinking water','Ασφαλώς διαχειριζόμενο πόσιμο νερό','% of population','housing,infrastructure','pp'),
 ('SH.STA.SMSS.ZS','Safely managed sanitation','Ασφαλώς διαχειριζόμενη αποχέτευση','% of population','housing,infrastructure','pp'),
 ('VC.IHR.PSRC.P5','Intentional homicides','Ανθρωποκτονίες εκ προθέσεως','per 100,000 people','security,justice','absolute'),
 ('SH.STA.TRAF.P5','Road traffic mortality','Θνησιμότητα από τροχαία','per 100,000 people','security,transport','absolute'),
 ('SP.POP.TOTL','Population','Πληθυσμός','people','demographics','absolute'),
 ('SP.DYN.TFRT.IN','Fertility rate','Δείκτης γονιμότητας','births per woman','demographics','absolute'),
 ('SP.POP.65UP.TO.ZS','Population aged 65+','Πληθυσμός 65 ετών και άνω','% of population','demographics','pp'),
 ('SP.POP.GROW','Population growth','Μεταβολή πληθυσμού','%','demographics','pp'),
 ('GC.TAX.TOTL.GD.ZS','Tax revenue','Φορολογικά έσοδα','% of GDP','finance','pp'),
 ('EG.FEC.RNEW.ZS','Renewable energy share','Μερίδιο ανανεώσιμων πηγών','% of final energy consumption','energy,resilience','pp'),
 ('EG.ELC.RNEW.ZS','Renewable electricity','Ηλεκτρισμός από ανανεώσιμες πηγές','% of electricity output','energy,environment','pp'),
 ('EG.IMP.CONS.ZS','Energy import dependence','Εξάρτηση από εισαγωγές ενέργειας','% of energy use','energy,resilience','pp'),
 ('IS.AIR.PSGR','Air transport passengers','Επιβάτες αερομεταφορών','passengers','transport,culture','absolute'),
 ('SG.GEN.PARL.ZS','Women in parliament','Γυναίκες στο κοινοβούλιο','% of seats','freedom,governance','pp'),
 ('GE.EST','Government effectiveness','Αποτελεσματικότητα διακυβέρνησης','WGI estimate','governance','absolute'),
 ('CC.EST','Control of corruption','Έλεγχος διαφθοράς','WGI estimate','governance,justice','absolute'),
 ('RL.EST','Rule of law','Κράτος δικαίου','WGI estimate','justice','absolute'),
 ('VA.EST','Voice & accountability','Φωνή πολιτών & λογοδοσία','WGI estimate','freedom,governance','absolute'),
 ('PV.EST','Political stability & absence of violence','Πολιτική σταθερότητα & απουσία βίας','WGI estimate','security,resilience','absolute'),
 ('RQ.EST','Regulatory quality','Ποιότητα κανονιστικού πλαισίου','WGI estimate','business,governance','absolute'),
]
# First audited expansion, 27 September 2026. Counts and rates stay separate.
ROWS += [
 ('FP.CPI.TOTL','Consumer price index','Δείκτης τιμών καταναλωτή','2010 = 100','economy,wellbeing','absolute'),
 ('NE.EXP.GNFS.CD','Exports, current value','Αξία εξαγωγών, τρέχουσες τιμές','current US$','economy,international','absolute'),
 ('SE.PRM.ENRR','Primary enrolment, gross','Εγγραφές στην πρωτοβάθμια, ακαθάριστο ποσοστό','%','education','pp'),
 ('SE.PRM.CMPT.ZS','Primary school completion','Ολοκλήρωση πρωτοβάθμιας εκπαίδευσης','% of relevant age group','education','pp'),
 ('SE.SEC.CMPT.LO.ZS','Lower-secondary completion','Ολοκλήρωση κατώτερης δευτεροβάθμιας','% of relevant age group','education','pp'),
 ('SE.PRM.TCHR.FE.ZS','Women among primary teachers','Γυναίκες εκπαιδευτικοί πρωτοβάθμιας','% of primary teachers','education,freedom','pp'),
 ('AG.LND.FRST.K2','Forest area, total','Συνολική δασική έκταση','km²','environment,resilience','absolute'),
 ('AG.LND.AGRI.ZS','Agricultural land share','Μερίδιο γεωργικής γης','% of land area','environment','pp'),
 ('ER.H2O.FWTL.K3','Freshwater withdrawals','Αντλήσεις γλυκού νερού','billion m³/year','environment,resilience','absolute'),
 ('IS.RRS.PASG.KM','Rail passenger distance','Επιβατικό έργο σιδηροδρόμων','million passenger-km','infrastructure,transport','absolute'),
 ('IS.AIR.GOOD.MT.K1','Air freight distance','Εμπορευματικό έργο αερομεταφορών','million tonne-km','infrastructure,transport','absolute'),
 ('SH.H2O.BASW.ZS','At least basic drinking water','Τουλάχιστον βασικές υπηρεσίες πόσιμου νερού','% of population','housing,infrastructure','pp'),
 ('BM.KLT.DINV.WD.GD.ZS','Foreign direct investment outflows','Εκροές άμεσων ξένων επενδύσεων','% of GDP','economy,business,international','pp'),
 ('IP.JRN.ARTC.SC','Scientific & technical articles','Επιστημονικά και τεχνικά άρθρα','articles','business,technology,education','absolute'),
 ('SL.GDP.PCAP.EM.KD','GDP per employed person','ΑΕΠ ανά εργαζόμενο','constant 2021 international $','business,economy','absolute'),
 ('EN.POP.DNST','Population density','Πυκνότητα πληθυσμού','people/km² of land','demographics,housing','absolute'),
 ('SP.DYN.CBRT.IN','Crude birth rate','Ακαθάριστος δείκτης γεννήσεων','births per 1,000 people','demographics','absolute'),
 ('SP.DYN.CDRT.IN','Crude death rate','Ακαθάριστος δείκτης θανάτων','deaths per 1,000 people','demographics,health','absolute'),
 ('SP.POP.DPND.OL','Old-age dependency ratio','Δείκτης εξάρτησης ηλικιωμένων','% of working-age population','demographics','pp'),
 ('SP.POP.DPND.YG','Youth dependency ratio','Δείκτης εξάρτησης νέων','% of working-age population','demographics','pp'),
 ('SP.POP.TOTL.FE.ZS','Female population share','Ποσοστό γυναικών στον πληθυσμό','% of population','demographics','pp'),
]
RESEARCH_IDS = dict(zip([r[0] for r in ROWS[-21:]], [7,10,22,26,27,30,36,38,39,44,46,59,63,66,68,122,123,124,126,127,129]))
DEFINITIONS_EL = {
 'FP.CPI.TOTL':'Δείκτης τιμών καταναλωτή με έτος βάσης 2010 = 100. Μετρά το επίπεδο τιμών, όχι τον ετήσιο ρυθμό πληθωρισμού.',
 'NE.EXP.GNFS.CD':'Εξαγωγές αγαθών και υπηρεσιών σε τρέχοντα δολάρια ΗΠΑ. Οι μεταβολές περιλαμβάνουν επιδράσεις τιμών και συναλλαγματικών ισοτιμιών· δεν μετρούν μόνο όγκο εξαγωγών.',
 'SE.PRM.ENRR':'Σύνολο εγγεγραμμένων στην πρωτοβάθμια, ανεξαρτήτως ηλικίας, ως ποσοστό του πληθυσμού της επίσημης ηλικίας φοίτησης. Μπορεί να υπερβαίνει το 100%.',
 'SE.PRM.CMPT.ZS':'Νέοι εισερχόμενοι στην τελευταία τάξη της πρωτοβάθμιας, χωρίς επαναλαμβάνοντες, ως ποσοστό του πληθυσμού της επίσημης ηλικίας εισόδου στην τάξη. Ο ακαθάριστος δείκτης μπορεί να υπερβαίνει το 100%.',
 'SE.SEC.CMPT.LO.ZS':'Νέοι εισερχόμενοι στην τελευταία τάξη της κατώτερης δευτεροβάθμιας, χωρίς επαναλαμβάνοντες, ως ποσοστό του πληθυσμού της αντίστοιχης επίσημης ηλικίας. Δεν είναι διαχρονική παρακολούθηση μιας μαθητικής γενιάς.',
 'SE.PRM.TCHR.FE.ZS':'Γυναίκες εκπαιδευτικοί ως ποσοστό του συνόλου των εκπαιδευτικών πρωτοβάθμιας εκπαίδευσης.',
 'AG.LND.FRST.K2':'Συνολική δασική έκταση σε τετραγωνικά χιλιόμετρα, σύμφωνα με τον ορισμό FAO. Δεν είναι ποσοστό της χώρας ούτε άμεση ετήσια μέτρηση αποψίλωσης.',
 'AG.LND.AGRI.ZS':'Γεωργική γη ως ποσοστό της χερσαίας έκτασης: αρόσιμη γη, μόνιμες καλλιέργειες και μόνιμοι βοσκότοποι.',
 'ER.H2O.FWTL.K3':'Ετήσιες αντλήσεις γλυκού νερού από υπόγειες και επιφανειακές πηγές, σε δισεκατομμύρια κυβικά μέτρα. Δεν είναι ο όγκος διαθέσιμων υδάτινων πόρων.',
 'IS.RRS.PASG.KM':'Επιβατικό έργο σιδηροδρόμων σε εκατομμύρια επιβατοχιλιόμετρα: επιβάτες επί διανυθείσα απόσταση. Δεν είναι αριθμός επιβατών.',
 'IS.AIR.GOOD.MT.K1':'Αεροπορικό εμπορευματικό έργο σε εκατομμύρια τονοχιλιόμετρα. Ακολουθεί την κάλυψη αερομεταφορέων του παρόχου· δεν είναι μόνο διακίνηση ελληνικών αεροδρομίων.',
 'SH.H2O.BASW.ZS':'Ποσοστό πληθυσμού με τουλάχιστον βασικές υπηρεσίες πόσιμου νερού: βελτιωμένη πηγή με χρόνο συλλογής έως 30 λεπτά με επιστροφή. Περιλαμβάνει και ασφαλώς διαχειριζόμενες υπηρεσίες.',
 'BM.KLT.DINV.WD.GD.ZS':'Καθαρές εκροές άμεσων ξένων επενδύσεων ως ποσοστό του ΑΕΠ. Αφορά επενδύσεις προς το εξωτερικό, όχι εισροές στη χώρα.',
 'IP.JRN.ARTC.SC':'Επιστημονικά και τεχνικά άρθρα στους κλάδους που καλύπτει η βιβλιομετρική πηγή της Παγκόσμιας Τράπεζας. Δεν περιλαμβάνει κάθε δημοσίευση ή κάθε επιστημονικό πεδίο.',
 'SL.GDP.PCAP.EM.KD':'ΑΕΠ ανά απασχολούμενο σε σταθερά διεθνή δολάρια 2021, με προσαρμογή ισοτιμίας αγοραστικής δύναμης. Είναι μέτρο παραγωγικότητας, όχι μισθού.',
 'EN.POP.DNST':'Πληθυσμός ανά τετραγωνικό χιλιόμετρο χερσαίας έκτασης, χωρίς εσωτερικά ύδατα.',
 'SP.DYN.CBRT.IN':'Ζώντες γεννήσεις ανά 1.000 κατοίκους σε ένα έτος. Δεν είναι γεννήσεις ανά γυναίκα.',
 'SP.DYN.CDRT.IN':'Θάνατοι ανά 1.000 κατοίκους σε ένα έτος. Ο δείκτης δεν είναι ηλικιακά προτυποποιημένος και επηρεάζεται από τη γήρανση του πληθυσμού.',
 'SP.POP.DPND.OL':'Πληθυσμός ηλικίας 65+ ως ποσοστό του πληθυσμού ηλικίας 15–64. Δημογραφικός λόγος, όχι αριθμός συνταξιούχων ανά εργαζόμενο.',
 'SP.POP.DPND.YG':'Πληθυσμός ηλικίας κάτω των 15 ετών ως ποσοστό του πληθυσμού ηλικίας 15–64. Δημογραφικός λόγος, όχι μέτρηση οικονομικής εξάρτησης.',
 'SP.POP.TOTL.FE.ZS':'Γυναίκες ως ποσοστό του συνολικού πληθυσμού, σύμφωνα με τις πληθυσμιακές εκτιμήσεις του παρόχου.',
}

# Second audited expansion: explicit units and research crosswalk.
ROWS += [('NY.GDP.MKTP.CD', 'GDP, current prices', 'ΑΕΠ σε τρέχουσες τιμές', 'current US$', 'economy', 'absolute'),
 ('NY.GDP.MKTP.PP.CD',
  'GDP at purchasing power parity',
  'ΑΕΠ σε ισοτιμία αγοραστικής δύναμης',
  'current international $',
  'economy',
  'absolute'),
 ('SH.ALC.PCAP.LI',
  'Alcohol consumption, ages 15+',
  'Κατανάλωση αλκοόλ, ηλικίες 15+',
  'litres of pure alcohol/person aged 15+',
  'health,wellbeing',
  'absolute'),
 ('SH.STA.ODFC.ZS',
  'Open defecation',
  'Αφόδευση σε ανοικτούς χώρους',
  '% of population',
  'housing,health',
  'pp'),
 ('SH.STA.BASS.UR.ZS',
  'Basic sanitation, urban population',
  'Βασική αποχέτευση στον αστικό πληθυσμό',
  '% of urban population',
  'housing,infrastructure',
  'pp'),
 ('SH.H2O.BASW.RU.ZS',
  'Basic drinking water, rural population',
  'Βασικό πόσιμο νερό στον αγροτικό πληθυσμό',
  '% of rural population',
  'housing,infrastructure',
  'pp'),
 ('SP.URB.TOTL.IN.ZS',
  'Urban population share',
  'Ποσοστό αστικού πληθυσμού',
  '% of population',
  'housing,demographics',
  'pp'),
 ('SM.POP.RHCR.EA',
  'Refugees hosted, UNHCR mandate',
  'Φιλοξενούμενοι πρόσφυγες υπό την εντολή της UNHCR',
  'people',
  'security,international',
  'absolute'),
 ('IT.MLT.MAIN.P2',
  'Fixed telephone subscriptions',
  'Συνδρομές σταθερής τηλεφωνίας',
  'per 100 people',
  'digital,infrastructure',
  'absolute'),
 ('FB.ATM.TOTL.P5',
  'ATM availability',
  'Διαθεσιμότητα ΑΤΜ',
  'ATMs per 100,000 adults',
  'digital,finance',
  'absolute'),
 ('SM.POP.TOTL',
  'International migrant stock',
  'Πληθυσμός διεθνών μεταναστών',
  'people',
  'demographics,international',
  'absolute'),
 ('GC.REV.XGRT.GD.ZS',
  'Government revenue excluding grants',
  'Κρατικά έσοδα χωρίς επιχορηγήσεις',
  '% of GDP',
  'finance',
  'pp'),
 ('DC.ODA.TLDC.CD',
  'Development aid to least developed countries',
  'Αναπτυξιακή βοήθεια προς λιγότερο ανεπτυγμένες χώρες',
  'current US$',
  'finance,international',
  'absolute'),
 ('SP.POP.SCIE.RD.P6',
  'Researchers per million people',
  'Ερευνητές ανά εκατομμύριο κατοίκους',
  'researchers (FTE) per million people',
  'technology,business,education',
  'absolute'),
 ('EG.EGY.PRIM.PP.KD',
  'Primary energy intensity',
  'Ένταση πρωτογενούς ενέργειας',
  'MJ per constant 2021 PPP $ of GDP',
  'energy,resilience',
  'absolute'),
 ('DC.ODA.TOTL.CD',
  'Net development aid provided',
  'Καθαρή αναπτυξιακή βοήθεια που παρέχεται',
  'current US$',
  'international,finance',
  'absolute'),
 ('FI.RES.TOTL.MO',
  'Reserves in months of imports',
  'Συναλλαγματικά διαθέσιμα σε μήνες εισαγωγών',
  'months of imports',
  'international,finance,resilience',
  'absolute')]
RESEARCH_IDS.update({'NY.GDP.MKTP.CD': 3, 'NY.GDP.MKTP.PP.CD': 3, 'SH.ALC.PCAP.LI': 76, 'SH.STA.ODFC.ZS': 94, 'SH.STA.BASS.UR.ZS': 96, 'SH.H2O.BASW.RU.ZS': 97, 'SP.URB.TOTL.IN.ZS': 99, 'SM.POP.RHCR.EA': 109, 'IT.MLT.MAIN.P2': 116, 'FB.ATM.TOTL.P5': 118, 'SM.POP.TOTL': 128, 'GC.REV.XGRT.GD.ZS': 134, 'DC.ODA.TLDC.CD': 140, 'SP.POP.SCIE.RD.P6': 142, 'EG.EGY.PRIM.PP.KD': 162, 'DC.ODA.TOTL.CD': 192, 'FI.RES.TOTL.MO': 200})
DEFINITIONS_EL.update({'NY.GDP.MKTP.CD': 'Συνολικό ΑΕΠ σε τρέχοντα δολάρια ΗΠΑ. Επηρεάζεται από τιμές και συναλλαγματικές '
                   'ισοτιμίες· δεν είναι πραγματική οικονομική μεγέθυνση.',
 'NY.GDP.MKTP.PP.CD': 'ΑΕΠ σε τρέχοντα διεθνή δολάρια με ισοτιμία αγοραστικής δύναμης. Δεν είναι σειρά '
                      'σταθερών τιμών.',
 'SH.ALC.PCAP.LI': 'Εκτιμώμενη συνολική ετήσια κατανάλωση καθαρής αλκοόλης ανά άτομο ηλικίας 15+, σε λίτρα. '
                   'Περιλαμβάνει καταγεγραμμένη και μη καταγεγραμμένη κατανάλωση· αφορά εκτιμήσεις του '
                   'παρόχου.',
 'SH.STA.ODFC.ZS': 'Ποσοστό πληθυσμού που αφοδεύει σε ανοικτούς χώρους, κατά τις εκτιμήσεις WHO/UNICEF. '
                   'Μηδενική τιμή δεν σημαίνει απουσία άλλων προβλημάτων αποχέτευσης.',
 'SH.STA.BASS.UR.ZS': 'Αστικός πληθυσμός με τουλάχιστον βασικές υπηρεσίες αποχέτευσης: βελτιωμένες '
                      'εγκαταστάσεις που δεν μοιράζονται με άλλα νοικοκυριά.',
 'SH.H2O.BASW.RU.ZS': 'Αγροτικός πληθυσμός με τουλάχιστον βασικές υπηρεσίες πόσιμου νερού: βελτιωμένη πηγή '
                      'με χρόνο συλλογής έως 30 λεπτά με επιστροφή.',
 'SP.URB.TOTL.IN.ZS': 'Πληθυσμός σε αστικές περιοχές ως ποσοστό του συνόλου. Οι εθνικοί ορισμοί του αστικού '
                      'πληθυσμού διαφέρουν.',
 'SM.POP.RHCR.EA': 'Πρόσφυγες υπό την εντολή της UNHCR ανά χώρα ασύλου. Είναι πληθυσμιακό απόθεμα, όχι '
                   'ετήσιες αφίξεις ή το σύνολο μεταναστών.',
 'IT.MLT.MAIN.P2': 'Συνδρομές σταθερής τηλεφωνίας ανά 100 κατοίκους. Μετρά συνδρομές, όχι μοναδικούς '
                   'χρήστες.',
 'FB.ATM.TOTL.P5': 'Αυτόματες ταμειολογιστικές μηχανές ανά 100.000 ενήλικους κατοίκους. Δεν είναι συνολικός '
                   'αριθμός ΑΤΜ.',
 'SM.POP.TOTL': 'Διεθνείς μετανάστες που διαμένουν στη χώρα, κυρίως βάσει χώρας γέννησης ή υπηκοότητας όπου '
                'απαιτείται. Είναι απόθεμα σε έτη αναφοράς, όχι ετήσιες μεταναστευτικές ροές· τα ενδιάμεσα '
                'κενά παραμένουν.',
 'GC.REV.XGRT.GD.ZS': 'Έσοδα χωρίς επιχορηγήσεις ως ποσοστό του ΑΕΠ, βάσει της σειράς δημοσιονομικών '
                      'στατιστικών της Παγκόσμιας Τράπεζας. Η θεσμική κάλυψη του παρόχου δεν ταυτίζεται κατ’ '
                      'ανάγκη με τη γενική κυβέρνηση της Eurostat.',
 'DC.ODA.TLDC.CD': 'Καθαρή επίσημη αναπτυξιακή βοήθεια που παρέχεται στις λιγότερο ανεπτυγμένες χώρες, σε '
                   'τρέχοντα δολάρια ΗΠΑ. Δεν είναι βοήθεια που λαμβάνει η χώρα.',
 'SP.POP.SCIE.RD.P6': 'Ερευνητές έρευνας και ανάπτυξης σε ισοδύναμα πλήρους απασχόλησης ανά εκατομμύριο '
                      'κατοίκους. Δεν είναι απλή καταμέτρηση προσώπων.',
 'EG.EGY.PRIM.PP.KD': 'Πρωτογενής ενέργεια ανά μονάδα ΑΕΠ σε σταθερά δολάρια 2021 αγοραστικής δύναμης. '
                      'Επηρεάζεται από τη δομή της οικονομίας, όχι μόνο από την ενεργειακή απόδοση.',
 'DC.ODA.TOTL.CD': 'Συνολική καθαρή επίσημη αναπτυξιακή βοήθεια που παρέχει η χώρα, σε τρέχοντα δολάρια ΗΠΑ. '
                   'Πρόκειται για καθαρές ροές.',
 'FI.RES.TOTL.MO': 'Συνολικά αποθεματικά εκφρασμένα σε μήνες εισαγωγών αγαθών και υπηρεσιών. Η συμμετοχή σε '
                   'νομισματική ένωση έχει σημασία για την ερμηνεία.'})
METRICS = [dict(code='GOV_WGI_'+c if c.endswith('.EST') else c,title={'en':en,'el':el},unit=u,categories=cat.split(','),change=change,source='3' if c.endswith('.EST') else '2',**({'researchId':RESEARCH_IDS[c],'definitionEl':DEFINITIONS_EL[c]} if c in RESEARCH_IDS else {})) for c,en,el,u,cat,change in ROWS]

CATEGORY_NOTES = {
 'culture': {'en':'Cultural employment, tourism and travel describe selected aspects of this category; they do not measure cultural quality.','el':'Πολιτιστική απασχόληση, τουρισμός και ταξίδια καλύπτουν επιμέρους πτυχές, όχι την ποιότητα του πολιτισμού.'},
 'international': {'en':'Trade, investment and tourism measure international engagement; they are not a reputation score.','el':'Εμπόριο, επενδύσεις και τουρισμός αποτυπώνουν τη διεθνή παρουσία· δεν αποτελούν δείκτη φήμης.'},
 'freedom': {'en':'Voice & accountability is a perception-based governance estimate, not a complete measure of individual freedoms.','el':'Η φωνή πολιτών και η λογοδοσία είναι εκτίμηση διακυβέρνησης βάσει αντιλήψεων, όχι πλήρης μέτρηση ατομικών ελευθεριών.'},
 'housing': {'en':'Housing cost overburden is the share of people in households spending more than 40% of disposable income on housing, net of housing allowances.','el':'Υπερβολική επιβάρυνση στέγασης: ποσοστό πληθυσμού σε νοικοκυριά που δαπανούν πάνω από 40% του διαθέσιμου εισοδήματος για στέγαση, μετά την αφαίρεση στεγαστικών επιδομάτων.'}
}
