"""Editorial labels and category mappings; all observations come from official APIs."""
COUNTRIES = {
    'GRC': {'en': 'Greece', 'el': 'Ελλάδα', 'color': '#086a88'},
    'EUU': {'en': 'European Union', 'el': 'Ευρωπαϊκή Ένωση', 'color': '#d69624'},
    'DEU': {'en': 'Germany', 'el': 'Γερμανία', 'color': '#6953a5'},
    'FRA': {'en': 'France', 'el': 'Γαλλία', 'color': '#b34f72'},
    'ESP': {'en': 'Spain', 'el': 'Ισπανία', 'color': '#d46534'},
    'PRT': {'en': 'Portugal', 'el': 'Πορτογαλία', 'color': '#32826e'},
}
CATEGORIES = [
 ('economy','Economy','Οικονομία'), ('health','Health','Υγεία'),
 ('education','Education','Παιδεία'), ('environment','Environment','Περιβάλλον'),
 ('infrastructure','Infrastructure','Υποδομές'), ('governance','Governance & society','Διακυβέρνηση & κοινωνία'),
 ('business','Business & innovation','Επιχειρήσεις & καινοτομία'),
 ('wellbeing','Well-being & quality of life','Ευημερία & ποιότητα ζωής'),
 ('culture','Culture & leisure','Πολιτισμός & αναψυχή'),
 ('housing','Housing & living conditions','Στέγαση & συνθήκες διαβίωσης'),
 ('security','Personal security & resilience','Ασφάλεια & ανθεκτικότητα'),
 ('digital','Digital society','Ψηφιακή κοινωνία'),
 ('demographics','Demographics & population','Δημογραφία & πληθυσμός'),
 ('finance','Public finance & debt','Δημόσια οικονομικά & χρέος'),
 ('technology','Technological readiness','Τεχνολογική ετοιμότητα'),
 ('justice','Justice & rule of law','Δικαιοσύνη & κράτος δικαίου'),
 ('energy','Energy & resources','Ενέργεια & πόροι'),
 ('transport','Transportation & mobility','Μεταφορές & κινητικότητα'),
 ('resilience','Resilience & sustainability','Ανθεκτικότητα & βιωσιμότητα'),
 ('international','International engagement','Διεθνής παρουσία'),
 ('freedom','Freedom & participation','Ελευθερία & συμμετοχή'),
]
# code, short English label, Greek label, unit, categories, change unit.
# Changes in percentages are percentage points, never percentage growth.
ROWS = [
 ('NY.GDP.MKTP.KD.ZG','GDP growth','Ανάπτυξη ΑΕΠ','%','economy','pp'),
 ('NY.GDP.PCAP.KD','GDP per capita','Κατά κεφαλήν ΑΕΠ','constant 2015 US$','economy,wellbeing','absolute'),
 ('FP.CPI.TOTL.ZG','Consumer price inflation','Πληθωρισμός','%','economy,wellbeing','pp'),
 ('SL.UEM.TOTL.ZS','Unemployment','Ανεργία','%','economy,wellbeing','pp'),
 ('SL.UEM.1524.ZS','Youth unemployment','Ανεργία νέων','%','economy,wellbeing','pp'),
 ('SL.TLF.CACT.FE.ZS','Female labour participation','Συμμετοχή γυναικών στην εργασία','%','economy,governance,freedom','pp'),
 ('NE.TRD.GNFS.ZS','Trade openness','Εμπόριο ως ποσοστό του ΑΕΠ','% of GDP','economy,international','pp'),
 ('BX.KLT.DINV.WD.GD.ZS','Foreign direct investment','Άμεσες ξένες επενδύσεις','% of GDP','economy,business,international','pp'),
 ('NE.EXP.GNFS.ZS','Exports of goods & services','Εξαγωγές αγαθών & υπηρεσιών','% of GDP','economy,international','pp'),
 ('SP.DYN.LE00.IN','Life expectancy','Προσδόκιμο ζωής','years','health,wellbeing','absolute'),
 ('SP.DYN.IMRT.IN','Infant mortality','Βρεφική θνησιμότητα','per 1,000 live births','health','absolute'),
 ('SH.STA.MMRT','Maternal mortality','Μητρική θνησιμότητα','per 100,000 live births','health','absolute'),
 ('SH.MED.BEDS.ZS','Hospital beds','Νοσοκομειακές κλίνες','per 1,000 people','health,infrastructure','absolute'),
 ('SH.XPD.CHEX.GD.ZS','Health expenditure','Δαπάνες υγείας','% of GDP','health,finance','pp'),
 ('SH.XPD.CHEX.PC.CD','Health spending per person','Δαπάνες υγείας ανά κάτοικο','current US$','health','absolute'),
 ('SH.IMM.MEAS','Measles immunisation','Εμβολιασμός ιλαράς','% of children 12–23 months','health,resilience','pp'),
 ('SE.XPD.TOTL.GD.ZS','Public education spending','Δημόσιες δαπάνες παιδείας','% of GDP','education,finance','pp'),
 ('SE.TER.ENRR','Tertiary enrolment, gross','Εγγραφές στην τριτοβάθμια, ακαθάριστο ποσοστό','%','education','pp'),
 ('SE.SEC.ENRR','Secondary enrolment, gross','Εγγραφές στη δευτεροβάθμια, ακαθάριστο ποσοστό','%','education','pp'),
 ('SE.PRM.ENRL.TC.ZS','Primary pupil–teacher ratio','Μαθητές ανά εκπαιδευτικό πρωτοβάθμιας','pupils per teacher','education','absolute'),
 ('AG.LND.FRST.ZS','Forest area','Δασική έκταση','% of land area','environment,resilience','pp'),
 ('EN.ATM.PM25.MC.M3','PM2.5 air pollution','Ατμοσφαιρική ρύπανση PM2.5','µg/m³','environment,health,housing','absolute'),
 ('EN.GHG.CO2.PC.CE.AR5','CO₂ emissions per person','Εκπομπές CO₂ ανά κάτοικο','t CO₂e/person','environment,energy,resilience','absolute'),
 ('ER.LND.PTLD.ZS','Protected terrestrial areas','Προστατευόμενες χερσαίες περιοχές','% of land area','environment,resilience','pp'),
 ('EG.ELC.ACCS.ZS','Access to electricity','Πρόσβαση σε ηλεκτρικό ρεύμα','% of population','infrastructure,housing','pp'),
 ('IT.NET.BBND.P2','Fixed broadband subscriptions','Συνδρομές σταθερής ευρυζωνικότητας','per 100 people','infrastructure,digital,technology','absolute'),
 ('IT.NET.USER.ZS','Internet use','Χρήση διαδικτύου','% of population','digital,technology','pp'),
 ('IT.CEL.SETS.P2','Mobile subscriptions','Συνδρομές κινητής τηλεφωνίας','per 100 people','digital,infrastructure','absolute'),
 ('IS.RRS.TOTL.KM','Rail network length','Μήκος σιδηροδρομικού δικτύου','km','infrastructure,transport','absolute'),
 ('GB.XPD.RSDV.GD.ZS','Research & development spending','Δαπάνες έρευνας & ανάπτυξης','% of GDP','business,technology','pp'),
 ('IP.PAT.RESD','Resident patent applications','Αιτήσεις διπλωμάτων ευρεσιτεχνίας κατοίκων','applications','business,technology','absolute'),
 ('TX.VAL.TECH.MF.ZS','High-technology exports','Εξαγωγές υψηλής τεχνολογίας','% of manufactured exports','business,technology,international','pp'),
 ('SI.POV.GINI','Income inequality (Gini)','Εισοδηματική ανισότητα (Gini)','0–100 index','wellbeing,governance','absolute'),
 ('ST.INT.ARVL','International tourist arrivals','Διεθνείς τουριστικές αφίξεις','arrivals','culture,international','absolute'),
 ('ST.INT.RCPT.CD','International tourism receipts','Έσοδα διεθνούς τουρισμού','current US$','culture,international','absolute'),
 ('SH.H2O.SMDW.ZS','Safely managed drinking water','Ασφαλώς διαχειριζόμενο πόσιμο νερό','% of population','housing,infrastructure','pp'),
 ('SH.STA.SMSS.ZS','Safely managed sanitation','Ασφαλώς διαχειριζόμενη αποχέτευση','% of population','housing,infrastructure','pp'),
 ('VC.IHR.PSRC.P5','Intentional homicides','Ανθρωποκτονίες εκ προθέσεως','per 100,000 people','security,justice','absolute'),
 ('SH.STA.TRAF.P5','Road traffic mortality','Θνησιμότητα από τροχαία','per 100,000 people','security,transport','absolute'),
 ('SP.POP.TOTL','Population','Πληθυσμός','people','demographics','absolute'),
 ('SP.DYN.TFRT.IN','Fertility rate','Δείκτης γονιμότητας','births per woman','demographics','absolute'),
 ('SP.POP.65UP.TO.ZS','Population aged 65+','Πληθυσμός 65 ετών και άνω','% of population','demographics','pp'),
 ('SP.POP.GROW','Population growth','Μεταβολή πληθυσμού','%','demographics','pp'),
 ('GC.TAX.TOTL.GD.ZS','Tax revenue','Φορολογικά έσοδα','% of GDP','finance','pp'),
 ('EG.FEC.RNEW.ZS','Renewable energy share','Μερίδιο ανανεώσιμων πηγών','% of final energy consumption','energy,resilience','pp'),
 ('EG.ELC.RNEW.ZS','Renewable electricity','Ηλεκτρισμός από ανανεώσιμες πηγές','% of electricity output','energy,environment','pp'),
 ('EG.IMP.CONS.ZS','Energy import dependence','Εξάρτηση από εισαγωγές ενέργειας','% of energy use','energy,resilience','pp'),
 ('IS.AIR.PSGR','Air transport passengers','Επιβάτες αερομεταφορών','passengers','transport,culture','absolute'),
 ('SG.GEN.PARL.ZS','Women in parliament','Γυναίκες στο κοινοβούλιο','% of seats','freedom,governance','pp'),
 ('GE.EST','Government effectiveness','Αποτελεσματικότητα διακυβέρνησης','WGI estimate','governance','absolute'),
 ('CC.EST','Control of corruption','Έλεγχος διαφθοράς','WGI estimate','governance,justice','absolute'),
 ('RL.EST','Rule of law','Κράτος δικαίου','WGI estimate','justice','absolute'),
 ('VA.EST','Voice & accountability','Φωνή πολιτών & λογοδοσία','WGI estimate','freedom,governance','absolute'),
 ('PV.EST','Political stability & absence of violence','Πολιτική σταθερότητα & απουσία βίας','WGI estimate','security,resilience','absolute'),
 ('RQ.EST','Regulatory quality','Ποιότητα κανονιστικού πλαισίου','WGI estimate','business,governance','absolute'),
]
METRICS = [dict(code='GOV_WGI_'+c if c.endswith('.EST') else c,title={'en':en,'el':el},unit=u,categories=cat.split(','),change=change,source='3' if c.endswith('.EST') else '2') for c,en,el,u,cat,change in ROWS]

CATEGORY_NOTES = {
 'culture': {'en':'Cultural employment, tourism and travel describe selected aspects of this category; they do not measure cultural quality.','el':'Πολιτιστική απασχόληση, τουρισμός και ταξίδια καλύπτουν επιμέρους πτυχές, όχι την ποιότητα του πολιτισμού.'},
 'international': {'en':'Trade, investment and tourism measure international engagement; they are not a reputation score.','el':'Εμπόριο, επενδύσεις και τουρισμός αποτυπώνουν τη διεθνή παρουσία· δεν αποτελούν δείκτη φήμης.'},
 'freedom': {'en':'Voice & accountability is a perception-based governance estimate, not a complete measure of individual freedoms.','el':'Η φωνή πολιτών και η λογοδοσία είναι εκτίμηση διακυβέρνησης βάσει αντιλήψεων, όχι πλήρης μέτρηση ατομικών ελευθεριών.'},
 'housing': {'en':'Housing cost overburden is the share of people in households spending more than 40% of disposable income on housing, net of housing allowances.','el':'Υπερβολική επιβάρυνση στέγασης: ποσοστό πληθυσμού σε νοικοκυριά που δαπανούν πάνω από 40% του διαθέσιμου εισοδήματος για στέγαση, μετά την αφαίρεση στεγαστικών επιδομάτων.'}
}
