"""Reviewed headline additions from the 3 October 2026 coverage audit.

Explicit definitions and dimensions; excludes duplicate variants and unverified sources.
"""

WORLD_BANK = [{'code': 'NE.GDI.FTOT.ZS',
  'title': {'en': 'Fixed investment', 'el': 'Επενδύσεις παγίου κεφαλαίου'},
  'unit': '% of GDP',
  'categories': ['economy'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Ακαθάριστος σχηματισμός παγίου κεφαλαίου ως ποσοστό του ΑΕΠ. Δεν περιλαμβάνει μεταβολές '
                  'αποθεμάτων.',
  'auditCode': 'NE.GDI.FTOT.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'NY.GNS.ICTR.ZS',
  'title': {'en': 'Gross savings', 'el': 'Ακαθάριστη αποταμίευση'},
  'unit': '% of GDP',
  'categories': ['economy'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Ακαθάριστη εθνική αποταμίευση ως ποσοστό του ΑΕΠ· δεν αφορά μόνο τις αποταμιεύσεις '
                  'νοικοκυριών.',
  'auditCode': 'NY.GNS.ICTR.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'NV.IND.MANF.ZS',
  'title': {'en': 'Manufacturing value added', 'el': 'Προστιθέμενη αξία μεταποίησης'},
  'unit': '% of GDP',
  'categories': ['economy'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Προστιθέμενη αξία του τομέα μεταποίησης ως ποσοστό του ΑΕΠ, με τον ορισμό του παρόχου.',
  'auditCode': 'NV.IND.MANF.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'BN.CAB.XOKA.GD.ZS',
  'title': {'en': 'Current account balance', 'el': 'Ισοζύγιο τρεχουσών συναλλαγών'},
  'unit': '% of GDP',
  'categories': ['economy'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Ισοζύγιο τρεχουσών συναλλαγών ως ποσοστό του ΑΕΠ. Περιλαμβάνει αγαθά, υπηρεσίες και '
                  'εισοδηματικές ροές· δεν είναι δημοσιονομικό ισοζύγιο.',
  'auditCode': 'BN.CAB.XOKA.GD.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'SL.EMP.TOTL.SP.ZS',
  'title': {'en': 'Employment-to-population ratio, ages 15+', 'el': 'Απασχόληση προς πληθυσμό, ηλικίες 15+'},
  'unit': '% of population ages 15+',
  'categories': ['jobs'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Απασχολούμενοι ως ποσοστό του πληθυσμού ηλικίας 15+, βάσει μοντελοποιημένων εκτιμήσεων '
                  'ILO. Δεν είναι ποσοστό επί του εργατικού δυναμικού.',
  'auditCode': 'SL.EMP.TOTL.SP.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'SL.EMP.SELF.ZS',
  'title': {'en': 'Self-employment share', 'el': 'Μερίδιο αυτοαπασχόλησης'},
  'unit': '% of employment',
  'categories': ['jobs'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Αυτοαπασχολούμενοι ως ποσοστό της συνολικής απασχόλησης, βάσει μοντελοποιημένων '
                  'εκτιμήσεων ILO. Περιλαμβάνονται οι κατηγορίες του ορισμού του παρόχου.',
  'auditCode': 'SL.EMP.SELF.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'SL.UEM.NEET.ZS',
  'title': {'en': 'Young people outside work, education or training',
            'el': 'Νέοι εκτός εργασίας, εκπαίδευσης ή κατάρτισης'},
  'unit': '% of population ages 15–24',
  'categories': ['jobs'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Νέοι ηλικίας 15–24 που δεν εργάζονται ούτε συμμετέχουν σε εκπαίδευση ή κατάρτιση, ως '
                  'ποσοστό όλων των νέων της ηλικιακής ομάδας.',
  'auditCode': 'SL.UEM.NEET.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'SH.DYN.MORT',
  'title': {'en': 'Under-five mortality', 'el': 'Θνησιμότητα παιδιών κάτω των 5 ετών'},
  'unit': 'per 1,000 live births',
  'categories': ['health'],
  'change': 'absolute',
  'source': '2',
  'definitionEl': 'Πιθανότητα θανάτου πριν από τα πέμπτα γενέθλια ανά 1.000 γεννήσεις ζώντων, βάσει '
                  'εκτιμήσεων του παρόχου.',
  'auditCode': 'SH.DYN.MORT',
  'reviewedOn': '2026-10-03'},
 {'code': 'SH.XPD.OOPC.CH.ZS',
  'title': {'en': 'Out-of-pocket health spending', 'el': 'Άμεσες ιδιωτικές πληρωμές για υγεία'},
  'unit': '% of current health expenditure',
  'categories': ['health'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Άμεσες πληρωμές νοικοκυριών ως ποσοστό της τρέχουσας δαπάνης υγείας. Δεν είναι ποσοστό '
                  'του εισοδήματος νοικοκυριών.',
  'auditCode': 'SH.XPD.OOPC.CH.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'SH.MED.PHYS.ZS',
  'title': {'en': 'Physicians per 1,000 people', 'el': 'Ιατροί ανά 1.000 κατοίκους'},
  'unit': 'physicians per 1,000 people',
  'categories': ['health'],
  'change': 'absolute',
  'source': '2',
  'definitionEl': 'Γενικοί και ειδικοί ιατροί ανά 1.000 κατοίκους. Η εθνική κάλυψη προσωπικού μπορεί να '
                  'διαφέρει· δεν μετρά άμεσα πρόσβαση ή ποιότητα φροντίδας.',
  'auditCode': 'SH.MED.PHYS.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'SH.DYN.NCOM.ZS',
  'title': {'en': 'Premature mortality from four major NCDs',
            'el': 'Πρόωρη θνησιμότητα από τέσσερις κύριες μη μεταδοτικές νόσους'},
  'unit': '% probability, ages 30–70',
  'categories': ['health'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Πιθανότητα θανάτου μεταξύ 30 και 70 ετών από καρδιαγγειακά νοσήματα, καρκίνο, διαβήτη ή '
                  'χρόνια αναπνευστικά νοσήματα, υπό τους τρέχοντες δείκτες θνησιμότητας. Δεν είναι μερίδιο '
                  'όλων των θανάτων.',
  'auditCode': 'SH.DYN.NCOM.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'SE.PRE.ENRR',
  'title': {'en': 'Preprimary enrolment, gross',
            'el': 'Εγγραφές στην προσχολική εκπαίδευση, ακαθάριστο ποσοστό'},
  'unit': '% gross enrolment',
  'categories': ['education'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Συνολικές εγγραφές στην προσχολική εκπαίδευση, ανεξαρτήτως ηλικίας, προς τον πληθυσμό της '
                  'επίσημης ηλικιακής ομάδας. Μπορεί να υπερβαίνει το 100%. Η τελευταία ελληνική παρατήρηση '
                  'έχει σημαντική υστέρηση.',
  'auditCode': 'SE.PRE.ENRR',
  'reviewedOn': '2026-10-03'},
 {'code': 'SM.POP.NETM',
  'title': {'en': 'Net migration', 'el': 'Καθαρή μετανάστευση'},
  'unit': 'people',
  'categories': ['demographics'],
  'change': 'absolute',
  'source': '2',
  'definitionEl': 'Μετανάστες που εισέρχονται μείον όσους εξέρχονται κατά την περίοδο αναφοράς, '
                  'συμπεριλαμβανομένων πολιτών και μη πολιτών. Είναι καθαρή ροή, όχι πληθυσμιακό απόθεμα.',
  'auditCode': 'SM.POP.NETM',
  'reviewedOn': '2026-10-03'},
 {'code': 'SP.URB.GROW',
  'title': {'en': 'Urban population growth', 'el': 'Αύξηση αστικού πληθυσμού'},
  'unit': '% annual growth',
  'categories': ['demographics'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Ετήσιος ρυθμός μεταβολής αστικού πληθυσμού. Οι εθνικοί ορισμοί αστικών περιοχών '
                  'διαφέρουν.',
  'auditCode': 'SP.URB.GROW',
  'reviewedOn': '2026-10-03'},
 {'code': 'EG.ELC.LOSS.ZS',
  'title': {'en': 'Electricity transmission and distribution losses',
            'el': 'Απώλειες μεταφοράς και διανομής ηλεκτρισμού'},
  'unit': '% of electricity output',
  'categories': ['environment'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Απώλειες στη μεταφορά και διανομή ως ποσοστό της παραγωγής ηλεκτρικής ενέργειας, σύμφωνα '
                  'με τον ορισμό του παρόχου.',
  'auditCode': 'EG.ELC.LOSS.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'ER.H2O.FWST.ZS',
  'title': {'en': 'Water stress', 'el': 'Υδατική πίεση'},
  'unit': '% of available freshwater resources',
  'categories': ['environment'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Απολήψεις γλυκού νερού ως ποσοστό διαθέσιμων ανανεώσιμων πόρων, αφού ληφθούν υπόψη οι '
                  'περιβαλλοντικές απαιτήσεις ροής. Δεν είναι οικιακή κατανάλωση νερού.',
  'auditCode': 'ER.H2O.FWST.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'IS.RRS.GOOD.MT.K6',
  'title': {'en': 'Rail freight', 'el': 'Σιδηροδρομικές εμπορευματικές μεταφορές'},
  'unit': 'million tonne-km',
  'categories': ['transport'],
  'change': 'absolute',
  'source': '2',
  'definitionEl': 'Όγκος σιδηροδρομικού εμπορευματικού έργου σε εκατομμύρια τονοχιλιόμετρα. Συνδυάζει βάρος '
                  'και απόσταση, όχι μόνο τόνους φορτίου.',
  'auditCode': 'IS.RRS.GOOD.MT.K6',
  'reviewedOn': '2026-10-03'},
 {'code': 'IS.SHP.GOOD.TU',
  'title': {'en': 'Container port traffic', 'el': 'Κίνηση εμπορευματοκιβωτίων λιμένων'},
  'unit': 'TEU',
  'categories': ['transport'],
  'change': 'absolute',
  'source': '2',
  'definitionEl': 'Διακίνηση εμπορευματοκιβωτίων σε ισοδύναμες μονάδες είκοσι ποδών (TEU), βάσει της κάλυψης '
                  'λιμένων του παρόχου. Δεν είναι βάρος φορτίου.',
  'auditCode': 'IS.SHP.GOOD.TU',
  'reviewedOn': '2026-10-03'},
 {'code': 'IS.AIR.DPRT',
  'title': {'en': 'Registered-carrier aircraft departures',
            'el': 'Αναχωρήσεις αεροσκαφών εγγεγραμμένων αερομεταφορέων'},
  'unit': 'departures',
  'categories': ['transport'],
  'change': 'absolute',
  'source': '2',
  'definitionEl': 'Παγκόσμιες αναχωρήσεις αερομεταφορέων εγγεγραμμένων στη χώρα. Δεν είναι όλες οι '
                  'αναχωρήσεις από τα αεροδρόμια της χώρας.',
  'auditCode': 'IS.AIR.DPRT',
  'reviewedOn': '2026-10-03'},
 {'code': 'FS.AST.PRVT.GD.ZS',
  'title': {'en': 'Domestic credit to private sector', 'el': 'Εγχώρια πίστωση προς ιδιωτικό τομέα'},
  'unit': '% of GDP',
  'categories': ['business'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Εγχώρια χρηματοδότηση του ιδιωτικού τομέα από χρηματοπιστωτικές επιχειρήσεις ως ποσοστό '
                  'του ΑΕΠ. Δεν είναι μόνο νέα δάνεια ενός έτους.',
  'auditCode': 'FS.AST.PRVT.GD.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'IC.BUS.NDNS.ZS',
  'title': {'en': 'New business density', 'el': 'Πυκνότητα νέων επιχειρήσεων'},
  'unit': 'registrations per 1,000 people ages 15–64',
  'categories': ['business'],
  'change': 'absolute',
  'source': '2',
  'definitionEl': 'Νέες εγγραφές εταιρειών περιορισμένης ευθύνης ανά 1.000 άτομα ηλικίας 15–64. Δεν '
                  'περιλαμβάνει κάθε μορφή επιχειρηματικής δραστηριότητας.',
  'auditCode': 'IC.BUS.NDNS.ZS',
  'reviewedOn': '2026-10-03'},
 {'code': 'TX.VAL.ICTG.ZS.UN',
  'title': {'en': 'ICT goods export share', 'el': 'Μερίδιο εξαγωγών αγαθών ΤΠΕ'},
  'unit': '% of goods exports',
  'categories': ['business'],
  'change': 'pp',
  'source': '2',
  'definitionEl': 'Αγαθά τεχνολογιών πληροφορικής και επικοινωνιών ως ποσοστό συνολικών εξαγωγών αγαθών. Δεν '
                  'περιλαμβάνει υπηρεσίες ΤΠΕ.',
  'auditCode': 'TX.VAL.ICTG.ZS.UN',
  'reviewedOn': '2026-10-03'},
 {'code': 'FB.CBK.BRCH.P5',
  'title': {'en': 'Commercial bank branch density', 'el': 'Πυκνότητα υποκαταστημάτων εμπορικών τραπεζών'},
  'unit': 'branches per 100,000 adults',
  'categories': ['business'],
  'change': 'absolute',
  'source': '2',
  'definitionEl': 'Φυσικά υποκαταστήματα εμπορικών τραπεζών ανά 100.000 ενήλικους κατοίκους. Δεν είναι μέτρο '
                  'ψηφιακής πρόσβασης ή ποιότητας τραπεζικών υπηρεσιών.',
  'auditCode': 'FB.CBK.BRCH.P5',
  'reviewedOn': '2026-10-03'}]

EUROSTAT = [{'code': 'ESTAT.POVERTY.RISK',
  'dataset': 'ilc_li02',
  'title': {'en': 'At risk of income poverty', 'el': 'Κίνδυνος εισοδηματικής φτώχειας'},
  'unit': '% of population',
  'categories': ['wellbeing'],
  'change': 'pp',
  'params': {'statinfo': 'MED_EI', 'unit': 'PC', 'rskpovth': 'B_60', 'sex': 'T', 'age': 'TOTAL'},
  'definition': 'People below 60% of national median equivalised disposable income after social transfers. '
                'Relative poverty, not an absolute living-standard threshold. EU-SILC income usually refers '
                'to the preceding year; retain survey-year labels and breaks.',
  'definitionEl': 'Πληθυσμός κάτω από το 60% του εθνικού διάμεσου ισοδύναμου διαθέσιμου εισοδήματος μετά τις '
                  'κοινωνικές μεταβιβάσεις. Σχετική φτώχεια, όχι απόλυτο όριο διαβίωσης. Το εισόδημα συνήθως '
                  'αφορά το προηγούμενο έτος· διατηρούνται τα έτη έρευνας και οι τομές.',
  'auditCode': 'ESTAT.NEW.01',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.POVERTY.AROPE',
  'dataset': 'ilc_peps01n',
  'title': {'en': 'At risk of poverty or social exclusion',
            'el': 'Κίνδυνος φτώχειας ή κοινωνικού αποκλεισμού'},
  'unit': '% of population',
  'categories': ['wellbeing'],
  'change': 'pp',
  'params': {'unit': 'PC', 'sex': 'T', 'age': 'TOTAL'},
  'definition': 'EU 2030 AROPE definition: at least one of income poverty, severe material and social '
                'deprivation, or very low household work intensity. Components overlap; do not add their '
                'rates. Not spliced with the older AROPE definition.',
  'definitionEl': 'Ορισμός AROPE ΕΕ 2030: τουλάχιστον μία από εισοδηματική φτώχεια, σοβαρή υλική και '
                  'κοινωνική στέρηση ή πολύ χαμηλή ένταση εργασίας. Τα επιμέρους ποσοστά επικαλύπτονται και '
                  'δεν αθροίζονται. Δεν συνδέεται με τον παλαιότερο ορισμό.',
  'auditCode': 'ESTAT.NEW.02',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.DEPRIVATION.SEVERE',
  'dataset': 'ilc_mdsd11',
  'title': {'en': 'Severe material and social deprivation', 'el': 'Σοβαρή υλική και κοινωνική στέρηση'},
  'unit': '% of population',
  'categories': ['wellbeing'],
  'change': 'pp',
  'params': {'unit': 'PC', 'sex': 'T', 'age': 'TOTAL'},
  'definition': 'People unable to afford at least seven of thirteen material and social items. This is the '
                'revised material and social deprivation measure, not the older nine-item measure.',
  'definitionEl': 'Άτομα που αδυνατούν οικονομικά να καλύψουν τουλάχιστον επτά από δεκατρία υλικά και '
                  'κοινωνικά αγαθά ή δραστηριότητες. Δεν είναι ο παλαιότερος δείκτης εννέα στοιχείων.',
  'auditCode': 'ESTAT.NEW.03',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.HOUSING.OVERCROWDING',
  'dataset': 'ilc_lvho05a',
  'title': {'en': 'Overcrowded housing', 'el': 'Συνωστισμός στην κατοικία'},
  'unit': '% of population',
  'categories': ['wellbeing'],
  'change': 'pp',
  'params': {'unit': 'PC', 'rskpovth': 'TOTAL', 'sex': 'T', 'age': 'TOTAL'},
  'definition': 'People in overcrowded dwellings under the Eurostat room requirement based on household '
                'size, ages and composition. All ages, both sexes, all income groups.',
  'definitionEl': 'Πληθυσμός σε κατοικίες με ανεπαρκή αριθμό δωματίων σύμφωνα με το μέγεθος, τις ηλικίες και '
                  'τη σύνθεση του νοικοκυριού. Όλες οι ηλικίες, φύλα και εισοδηματικές ομάδες.',
  'auditCode': 'ESTAT.NEW.04',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.HOUSING.WARMTH',
  'dataset': 'ilc_mdes01',
  'title': {'en': 'Unable to keep home adequately warm', 'el': 'Αδυναμία επαρκούς θέρμανσης κατοικίας'},
  'unit': '% of population',
  'categories': ['wellbeing'],
  'change': 'pp',
  'params': {'hhcomp': 'TOTAL', 'rskpovth': 'TOTAL', 'unit': 'PC'},
  'definition': 'People in households reporting inability to afford adequate home warmth. EU-SILC '
                'self-reported affordability measure, not measured indoor temperature.',
  'definitionEl': 'Άτομα σε νοικοκυριά που δηλώνουν οικονομική αδυναμία επαρκούς θέρμανσης. Αυτοαναφερόμενος '
                  'δείκτης EU-SILC, όχι μέτρηση θερμοκρασίας.',
  'auditCode': 'ESTAT.NEW.05',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.HOUSEHOLDS.SIZE',
  'dataset': 'ilc_lvph01',
  'title': {'en': 'Average household size', 'el': 'Μέσο μέγεθος νοικοκυριού'},
  'unit': 'people per household',
  'categories': ['wellbeing'],
  'change': 'absolute',
  'params': {'unit': 'AVG'},
  'definition': 'Average number of people per private household. Excludes institutional households under the '
                'survey definition.',
  'definitionEl': 'Μέσος αριθμός ατόμων ανά ιδιωτικό νοικοκυριό. Εξαιρούνται συλλογικά νοικοκυριά βάσει του '
                  'ορισμού της έρευνας.',
  'auditCode': 'ESTAT.NEW.06',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.INCOME.MEDIAN',
  'dataset': 'ilc_di03',
  'title': {'en': 'Median equivalised disposable income', 'el': 'Διάμεσο ισοδύναμο διαθέσιμο εισόδημα'},
  'unit': 'EUR per year',
  'categories': ['wellbeing'],
  'change': 'absolute',
  'params': {'age': 'TOTAL', 'sex': 'T', 'statinfo': 'MED_EI', 'unit': 'EUR'},
  'definition': 'Median annual equivalised disposable income in nominal euros, all ages and both sexes. '
                'Adjusted for household composition, not inflation or purchasing power. Income reference '
                'period is usually the previous calendar year.',
  'definitionEl': 'Διάμεσο ετήσιο ισοδύναμο διαθέσιμο εισόδημα σε ονομαστικά ευρώ. Προσαρμόζεται στη σύνθεση '
                  'νοικοκυριού, όχι στον πληθωρισμό ή στην αγοραστική δύναμη. Το εισόδημα συνήθως αφορά το '
                  'προηγούμενο ημερολογιακό έτος.',
  'auditCode': 'ESTAT.NEW.07',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.EDUCATION.EARLY.LEAVERS',
  'dataset': 'sdg_04_10',
  'title': {'en': 'Early school leavers, ages 18–24', 'el': 'Πρόωρη εγκατάλειψη εκπαίδευσης, ηλικίες 18–24'},
  'unit': '% of population ages 18–24',
  'categories': ['education'],
  'change': 'pp',
  'params': {'unit': 'PC', 'wstatus': 'POP', 'age': 'Y18-24', 'sex': 'T'},
  'definition': 'People aged 18–24 with at most lower secondary education and no education or training in '
                'the preceding four weeks. EU Labour Force Survey; retain methodology breaks.',
  'definitionEl': 'Άτομα 18–24 με εκπαίδευση έως κατώτερη δευτεροβάθμια που δεν συμμετείχαν σε εκπαίδευση ή '
                  'κατάρτιση τις προηγούμενες τέσσερις εβδομάδες. Διατηρούνται οι μεθοδολογικές τομές της '
                  'Έρευνας Εργατικού Δυναμικού.',
  'auditCode': 'ESTAT.NEW.09',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.EDUCATION.TERTIARY.ATTAINMENT',
  'dataset': 'sdg_04_20',
  'title': {'en': 'Tertiary attainment, ages 25–34', 'el': 'Τριτοβάθμια εκπαίδευση, ηλικίες 25–34'},
  'unit': '% of population ages 25–34',
  'categories': ['education'],
  'change': 'pp',
  'params': {'unit': 'PC', 'age': 'Y25-34', 'sex': 'T', 'isced11': 'ED5-8'},
  'definition': 'People aged 25–34 who have completed tertiary education, ISCED levels 5–8. Attainment, not '
                'current enrolment.',
  'definitionEl': 'Άτομα 25–34 που έχουν ολοκληρώσει τριτοβάθμια εκπαίδευση, επίπεδα ISCED 5–8. Μετρά '
                  'ολοκληρωμένες σπουδές, όχι τρέχουσες εγγραφές.',
  'auditCode': 'ESTAT.NEW.10',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.HOTELS.NONRESIDENT.NIGHTS',
  'dataset': 'tour_occ_ninat',
  'title': {'en': 'Non-resident hotel nights', 'el': 'Διανυκτερεύσεις μη κατοίκων σε ξενοδοχεία'},
  'unit': 'nights',
  'categories': ['culture'],
  'change': 'absolute',
  'params': {'c_resid': 'FOR', 'unit': 'NR', 'nace_r2': 'I551'},
  'definition': 'Nights spent by non-residents in hotels and similar accommodation, NACE I551. Counts '
                'nights, not unique visitors; excludes other accommodation types.',
  'definitionEl': 'Διανυκτερεύσεις μη κατοίκων σε ξενοδοχεία και παρόμοια καταλύματα, NACE I551. Δεν είναι '
                  'μοναδικοί επισκέπτες και εξαιρούνται άλλοι τύποι καταλυμάτων.',
  'auditCode': 'ESTAT.NEW.15',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.TOUR.TRIPS.ABROAD',
  'dataset': 'tour_dem_tttot',
  'title': {'en': 'Resident overnight trips abroad', 'el': 'Ταξίδια κατοίκων στο εξωτερικό με διανυκτέρευση'},
  'unit': 'trips',
  'categories': ['culture'],
  'change': 'absolute',
  'params': {'c_dest': 'FOR', 'purpose': 'TOTAL', 'duration': 'N_GE1', 'unit': 'NR'},
  'definition': 'Trips abroad by residents aged 15+, all purposes, lasting at least one night. Trips rather '
                'than unique travellers or inbound tourism.',
  'definitionEl': 'Ταξίδια στο εξωτερικό από κατοίκους ηλικίας 15+, για όλους τους σκοπούς, με τουλάχιστον '
                  'μία διανυκτέρευση. Μετρά ταξίδια, όχι μοναδικούς ταξιδιώτες ή εισερχόμενο τουρισμό.',
  'auditCode': 'ESTAT.NEW.16',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.JUSTICE.JUDGES',
  'dataset': 'crim_just_job',
  'title': {'en': 'Professional judges', 'el': 'Επαγγελματίες δικαστές'},
  'unit': 'judges',
  'categories': ['governance'],
  'change': 'absolute',
  'params': {'isco08': 'OC2612A', 'sex': 'T', 'unit': 'NR'},
  'definition': 'Professional judges, both sexes, Eurostat justice personnel category OC2612A. Absolute '
                'staffing count, not a measure of judicial independence or court efficiency. National '
                'institutional definitions may differ.',
  'definitionEl': 'Επαγγελματίες δικαστές και των δύο φύλων, κατηγορία OC2612A. Απόλυτος αριθμός προσωπικού, '
                  'όχι μέτρο ανεξαρτησίας ή αποτελεσματικότητας. Οι εθνικοί θεσμικοί ορισμοί μπορεί να '
                  'διαφέρουν.',
  'auditCode': 'ESTAT.NEW.18',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.JUSTICE.PRISON.RATE',
  'dataset': 'crim_pris_cap',
  'title': {'en': 'Prison population rate', 'el': 'Κρατούμενοι ανά 100.000 κατοίκους'},
  'unit': 'per 100,000 people',
  'categories': ['governance'],
  'change': 'absolute',
  'params': {'indic_cr': 'PRIS_ACT_CAP', 'unit': 'P_HTHAB'},
  'definition': 'People held in prison per 100,000 inhabitants, Eurostat PRIS_ACT_CAP. A population stock, '
                'not annual admissions, prison capacity or a crime rate. National scope differences and '
                'flags apply.',
  'definitionEl': 'Κρατούμενοι ανά 100.000 κατοίκους, δείκτης PRIS_ACT_CAP. Πληθυσμιακό απόθεμα, όχι ετήσιες '
                  'εισαγωγές, χωρητικότητα φυλακών ή δείκτης εγκληματικότητας. Ισχύουν εθνικές διαφορές '
                  'κάλυψης.',
  'auditCode': 'ESTAT.NEW.20',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.MOTHERS.FIRST.AGE',
  'dataset': 'demo_find',
  'title': {'en': 'Mean age at first childbirth', 'el': 'Μέση ηλικία μητέρας στην πρώτη γέννηση'},
  'unit': 'years',
  'categories': ['demographics'],
  'change': 'absolute',
  'params': {'indic_de': 'AGEMOTH1'},
  'definition': 'Mean age of women at the birth of their first child, using age-specific first-birth '
                'fertility rates. Distinct from age at all childbirths.',
  'definitionEl': 'Μέση ηλικία γυναικών στην πρώτη γέννηση, βάσει ειδικών κατά ηλικία δεικτών πρώτης '
                  'γέννησης. Διαφέρει από τη μέση ηλικία για όλες τις γεννήσεις.',
  'auditCode': 'ESTAT.NEW.22',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.GOV.REVENUE',
  'dataset': 'gov_10a_main',
  'title': {'en': 'General government revenue', 'el': 'Έσοδα γενικής κυβέρνησης'},
  'unit': '% of GDP',
  'categories': ['finance'],
  'change': 'pp',
  'params': {'unit': 'PC_GDP', 'sector': 'S13', 'na_item': 'TR'},
  'definition': 'Total revenue of general government, sector S13, ESA 2010, as a percentage of GDP. Broader '
                'institutional scope than central-government revenue.',
  'definitionEl': 'Συνολικά έσοδα γενικής κυβέρνησης, τομέας S13, ESA 2010, ως ποσοστό του ΑΕΠ. Ευρύτερη '
                  'θεσμική κάλυψη από τα έσοδα μόνο της κεντρικής κυβέρνησης.',
  'auditCode': 'ESTAT.NEW.24',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.GOV.INTEREST',
  'dataset': 'gov_10a_main',
  'title': {'en': 'Government interest expenditure', 'el': 'Δαπάνες τόκων γενικής κυβέρνησης'},
  'unit': '% of GDP',
  'categories': ['finance'],
  'change': 'pp',
  'params': {'unit': 'PC_GDP', 'sector': 'S13', 'na_item': 'D41PAY'},
  'definition': 'Interest payable by general government, ESA 2010 D41PAY, as a percentage of GDP. Interest '
                'expense, not principal repayments or a bond yield.',
  'definitionEl': 'Πληρωτέοι τόκοι γενικής κυβέρνησης, ESA 2010 D41PAY, ως ποσοστό του ΑΕΠ. Δεν είναι '
                  'αποπληρωμές κεφαλαίου ή απόδοση ομολόγου.',
  'auditCode': 'ESTAT.NEW.25',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.GOV.SOCIAL.PROTECTION',
  'dataset': 'gov_10a_exp',
  'title': {'en': 'Government social protection spending', 'el': 'Δαπάνες κοινωνικής προστασίας'},
  'unit': '% of GDP',
  'categories': ['finance'],
  'change': 'pp',
  'params': {'unit': 'PC_GDP', 'sector': 'S13', 'cofog99': 'GF10', 'na_item': 'TE'},
  'definition': 'General government expenditure on social protection, COFOG GF10, as a percentage of GDP. '
                'Functional expenditure including pensions; not an outcome or poverty-reduction score.',
  'definitionEl': 'Δαπάνες γενικής κυβέρνησης για κοινωνική προστασία, COFOG GF10, ως ποσοστό του ΑΕΠ. '
                  'Περιλαμβάνει συντάξεις· δεν αποτελεί μέτρο αποτελέσματος ή μείωσης φτώχειας.',
  'auditCode': 'ESTAT.NEW.26',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.GOV.CULTURE.RECREATION',
  'dataset': 'gov_10a_exp',
  'title': {'en': 'Recreation, culture and religion spending',
            'el': 'Δαπάνες αναψυχής, πολιτισμού και θρησκείας'},
  'unit': '% of GDP',
  'categories': ['culture'],
  'change': 'pp',
  'params': {'unit': 'PC_GDP', 'sector': 'S13', 'cofog99': 'GF08', 'na_item': 'TE'},
  'definition': 'General government expenditure, COFOG GF08, as a percentage of GDP. Includes recreation, '
                'sport and religion as well as culture; do not label as culture-only expenditure.',
  'definitionEl': 'Δαπάνες γενικής κυβέρνησης, COFOG GF08, ως ποσοστό του ΑΕΠ. Περιλαμβάνει αναψυχή, '
                  'αθλητισμό και θρησκεία· δεν αφορά αποκλειστικά πολιτισμό.',
  'auditCode': 'ESTAT.NEW.27',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.GOV.ENVIRONMENT',
  'dataset': 'gov_10a_exp',
  'title': {'en': 'Government environmental protection spending', 'el': 'Δαπάνες περιβαλλοντικής προστασίας'},
  'unit': '% of GDP',
  'categories': ['finance'],
  'change': 'pp',
  'params': {'unit': 'PC_GDP', 'sector': 'S13', 'cofog99': 'GF05', 'na_item': 'TE'},
  'definition': 'General government expenditure on environmental protection, COFOG GF05, as a percentage of '
                'GDP. Functional spending, not all climate-related investment.',
  'definitionEl': 'Δαπάνες γενικής κυβέρνησης για περιβαλλοντική προστασία, COFOG GF05, ως ποσοστό του ΑΕΠ. '
                  'Δεν περιλαμβάνει αναγκαστικά όλες τις επενδύσεις για το κλίμα.',
  'auditCode': 'ESTAT.NEW.28',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.GOV.HOUSING',
  'dataset': 'gov_10a_exp',
  'title': {'en': 'Housing and community amenities spending', 'el': 'Δαπάνες στέγασης και κοινής ωφέλειας'},
  'unit': '% of GDP',
  'categories': ['finance'],
  'change': 'pp',
  'params': {'unit': 'PC_GDP', 'sector': 'S13', 'cofog99': 'GF06', 'na_item': 'TE'},
  'definition': 'General government expenditure on housing and community amenities, COFOG GF06, as a '
                'percentage of GDP. Not all housing benefits, which can fall under social protection.',
  'definitionEl': 'Δαπάνες γενικής κυβέρνησης για στέγαση και υποδομές κοινής ωφέλειας, COFOG GF06, ως '
                  'ποσοστό του ΑΕΠ. Δεν περιλαμβάνει όλα τα στεγαστικά επιδόματα, που μπορεί να '
                  'κατατάσσονται στην κοινωνική προστασία.',
  'auditCode': 'ESTAT.NEW.29',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.RENEWABLES.TRANSPORT',
  'dataset': 'nrg_ind_ren',
  'title': {'en': 'Renewable energy in transport', 'el': 'Ανανεώσιμη ενέργεια στις μεταφορές'},
  'unit': '% of transport energy consumption',
  'categories': ['environment'],
  'change': 'pp',
  'params': {'nrg_bal': 'REN_TRA', 'unit': 'PC'},
  'definition': 'Renewable energy share in transport under the EU Renewable Energy Directive accounting '
                'rules. Multipliers and methodology changes mean this is not a simple physical fuel-volume '
                'share.',
  'definitionEl': 'Μερίδιο ανανεώσιμης ενέργειας στις μεταφορές σύμφωνα με την ευρωπαϊκή οδηγία. Συντελεστές '
                  'και μεθοδολογικές αλλαγές σημαίνουν ότι δεν είναι απλό φυσικό μερίδιο όγκου καυσίμων.',
  'auditCode': 'ESTAT.NEW.30',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.RENEWABLES.HEATING',
  'dataset': 'nrg_ind_ren',
  'title': {'en': 'Renewable heating and cooling', 'el': 'Ανανεώσιμη ενέργεια στη θέρμανση και ψύξη'},
  'unit': '% of heating and cooling energy consumption',
  'categories': ['environment'],
  'change': 'pp',
  'params': {'nrg_bal': 'REN_HEAT_CL', 'unit': 'PC'},
  'definition': 'Renewable share of energy used for heating and cooling, Eurostat SHARES / Renewable Energy '
                'Directive methodology. Retain provider breaks.',
  'definitionEl': 'Μερίδιο ανανεώσιμης ενέργειας στη θέρμανση και ψύξη, βάσει Eurostat SHARES και της '
                  'ευρωπαϊκής οδηγίας. Διατηρούνται οι μεθοδολογικές τομές.',
  'auditCode': 'ESTAT.NEW.31',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.CARS.ELECTRIC.REGISTRATIONS',
  'dataset': 'road_eqr_carpda',
  'title': {'en': 'New battery-electric car registrations',
            'el': 'Νέες ταξινομήσεις αμιγώς ηλεκτρικών αυτοκινήτων'},
  'unit': 'registrations',
  'categories': ['transport'],
  'change': 'absolute',
  'params': {'mot_nrg': 'ELC', 'unit': 'NR'},
  'definition': 'New registrations of battery-electric passenger cars, energy category ELC. Excludes plug-in '
                'hybrids. Registrations are not sales; this is an explicitly labelled alternative to the '
                'thesis sales request.',
  'definitionEl': 'Νέες ταξινομήσεις αμιγώς ηλεκτρικών επιβατικών αυτοκινήτων, κατηγορία ELC. Εξαιρούνται τα '
                  'επαναφορτιζόμενα υβριδικά. Οι ταξινομήσεις δεν ταυτίζονται με πωλήσεις· πρόκειται για '
                  'ρητά διακριτό εναλλακτικό δείκτη.',
  'auditCode': 'ESTAT.NEW.33',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.UNEMPLOYMENT.LONGTERM',
  'dataset': 'une_ltu_a',
  'title': {'en': 'Long-term unemployment rate', 'el': 'Μακροχρόνια ανεργία'},
  'unit': '% of labour force ages 15–74',
  'categories': ['jobs'],
  'change': 'pp',
  'params': {'indic_em': 'LTU', 'age': 'Y15-74', 'sex': 'T', 'unit': 'PC_ACT'},
  'definition': 'Unemployed for 12 months or more as a percentage of the active population aged 15–74, both '
                'sexes. Denominator is the labour force, not all unemployed people.',
  'definitionEl': 'Άνεργοι επί 12 μήνες ή περισσότερο ως ποσοστό του εργατικού δυναμικού 15–74, και των δύο '
                  'φύλων. Παρονομαστής είναι το εργατικό δυναμικό, όχι το σύνολο των ανέργων.',
  'auditCode': 'ESTAT.NEW.39',
  'reviewedOn': '2026-10-03'},
 {'code': 'ESTAT.SALARY.FTE',
  'dataset': 'nama_10_fte',
  'title': {'en': 'Average annual full-time adjusted salary',
            'el': 'Μέσος ετήσιος μισθός προσαρμοσμένος σε πλήρη απασχόληση'},
  'unit': 'EUR per year',
  'categories': ['jobs'],
  'change': 'absolute',
  'params': {'unit': 'EUR'},
  'definition': 'Average annual salary per employee adjusted to full-time work, national accounts and Labour '
                'Force Survey methodology. Nominal gross euros; not median pay, take-home income or '
                'inflation-adjusted purchasing power.',
  'definitionEl': 'Μέσος ετήσιος μισθός ανά μισθωτό προσαρμοσμένος σε πλήρη απασχόληση, βάσει εθνικών '
                  'λογαριασμών και Έρευνας Εργατικού Δυναμικού. Ονομαστικά μικτά ευρώ, όχι διάμεσος ή '
                  'καθαρός μισθός ούτε πραγματική αγοραστική δύναμη.',
  'auditCode': 'ESTAT.SALARY.FTE',
  'reviewedOn': '2026-10-03'}]
